# tools/check-plugin-define-constraints.ps1 — the Unity MCP bridge stays out of every player.
#
# WHY THIS GATE EXISTS
#
# A managed plugin under Assets/Plugins/ is included in a build unless its .meta excludes it, and
# the exclusion this project relies on is `defineConstraints: [UNITY_EDITOR]` — true in the Editor,
# never true in a player of any target. `EditorBuild.StripEditorOnlyDefines` documents the other
# half: the MCP package writes UNITY_MCP_READY into EVERY platform's define set, so the builds
# strip it to keep the MCP assembly itself out.
#
# The failure this gate catches is the INCONSISTENT half of that arrangement. When one DLL of the
# bridge is left unconstrained while the DLLs it references are constrained, every player build
# includes the first, excludes the rest, and dies in the managed linker with
#
#     Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'R3'
#
# which names R3 — the file that is correct — and never names McpPlugin.dll, the file that is wrong.
#
# MEASURED, 2026-08-25. `com.ivanmurzak.unity.mcp` 0.90.0 and its ten extension packages (#175)
# installed McpPlugin.dll and McpPlugin.Common.dll with `defineConstraints: []`, while every other
# DLL of the same closure — R3, ReflectorNet, SignalR, Microsoft.CodeAnalysis — carried
# `- UNITY_EDITOR`. McpPlugin.dll references R3. The lane-B Windows player could not be built at
# all, and neither could the shipping Linux dedicated server: defineConstraints are evaluated per
# target and UNITY_EDITOR is false in both. Four days, nothing noticed.
#
# It is also a shipping question and not only a compile one. The bridge speaks HTTP and compiles
# arbitrary C# through Roslyn; an unconstrained McpPlugin.dll is that bridge inside the game server
# image, which is the concern EditorBuild.StripEditorOnlyDefines was written for.
#
# WHY A GATE AND NOT A ONE-TIME FIX. These .meta files are generated by the MCP package's own NuGet
# installer, whose manifest is Assets/Plugins/NuGet/.nuget-installed.json. The next package upgrade
# rewrites them, and a hand-fix is silently undone. A fix without this gate has an expiry date.
#
# WHY CI CANNOT OTHERWISE SEE IT. No CI job builds a Unity player — `images.yml`'s game-server job
# downloads a pre-built Linux artifact from a release, and `build-test` is `dotnet build` over the
# pure-.NET libraries, which never reads Assets/Plugins. The first thing that notices is a human
# building a release, which is the worst possible moment to find out.
#
# WHAT IT CHECKS, EXACTLY. Every DLL that the NuGet manifest attributes to a `com.IvanMurzak.*`
# package must carry `- UNITY_EDITOR`. The package list is read from the manifest rather than
# hardcoded, so a future MCP upgrade that adds a fourth bridge DLL is covered on the day it lands.
#
# WHAT IT DELIBERATELY DOES NOT CHECK. It does not walk assembly references looking for
# player-included DLLs that reference editor-only ones. That was the first version of this gate and
# it reported 22 violations against a tree whose player build SUCCEEDS: the BCL shims in this folder
# (System.Memory, System.Buffers, System.Numerics.Vectors, System.Threading.Tasks.Extensions)
# reference each other, and in a player those names resolve against Unity's own netstandard2.1
# profile rather than against the excluded plugin copies — see the $unityProvided block in
# tools/build-libs.ps1 for the same fact from the other direction. Deciding which names Unity
# provides needs the Editor's playback-engine assembly set, which CI does not have. A gate that
# cannot tell a real break from a backfilled shim is a gate that gets deleted by the first person
# it blocks, so this one answers the narrower question truthfully instead.
#
# Usage:  pwsh tools/check-plugin-define-constraints.ps1 [-ProjectPath Ironfront_Reborn]

[CmdletBinding()]
param(
    [string]$ProjectPath = "Ironfront_Reborn"
)

$ErrorActionPreference = "Stop"

$repoRoot    = Split-Path -Parent $PSScriptRoot
$nugetRel    = "$ProjectPath/Assets/Plugins/NuGet"
$nugetAbs    = Join-Path $repoRoot $nugetRel
$manifestAbs = Join-Path $nugetAbs ".nuget-installed.json"

# The bridge's own packages. Everything else in the manifest is a third-party dependency that may
# legitimately be shared with the game (System.Text.Json is, through Ironfront.Net.Configuration).
$bridgePackagePrefix = "com.IvanMurzak."

if (-not (Test-Path $manifestAbs)) {
    # No manifest means the MCP package is not installed in this checkout. That is a valid state —
    # the bridge is developer tooling — and nothing is being shipped wrongly.
    Write-Host "[plugin-constraints] no $nugetRel/.nuget-installed.json — MCP not installed, nothing to check."
    exit 0
}

$manifest = Get-Content -LiteralPath $manifestAbs -Raw | ConvertFrom-Json

# An empty or shapeless manifest must not read as a pass: that is the difference between "checked,
# clean" and "checked nothing", and only one of them is evidence.
if (-not $manifest.packages) {
    Write-Host "[plugin-constraints] FAIL — $nugetRel/.nuget-installed.json has no 'packages' object."
    Write-Host "The manifest format changed, or the file is truncated. This gate cannot see the"
    Write-Host "bridge DLLs and is reporting that rather than passing vacuously."
    exit 1
}

$expected = @()   # DLLs the manifest attributes to the bridge

foreach ($package in $manifest.packages.PSObject.Properties) {
    if (-not $package.Name.StartsWith($bridgePackagePrefix, [StringComparison]::OrdinalIgnoreCase)) { continue }

    foreach ($dll in $package.Value.dlls) {
        $expected += [pscustomobject]@{ Package = $package.Name; Dll = $dll }
    }
}

if ($expected.Count -eq 0) {
    Write-Host "[plugin-constraints] FAIL — the manifest lists $($manifest.packages.PSObject.Properties.Count) package(s) but none named $bridgePackagePrefix*."
    Write-Host "The bridge packages were renamed, or the manifest is for a different installer."
    Write-Host "Update `$bridgePackagePrefix in this gate; do not silently pass."
    exit 1
}

$editorOnlyPattern = '^\s*-\s*UNITY_EDITOR\s*$'
$violations = @()
$missing    = @()

foreach ($item in $expected | Sort-Object Dll) {
    $meta = Join-Path $nugetAbs "$($item.Dll).meta"

    if (-not (Test-Path $meta)) {
        # A bridge DLL with no .meta is Unity's cue to generate one — unconstrained, by default.
        $missing += $item
        continue
    }

    if (($Get = Get-Content -LiteralPath $meta | Where-Object { $_ -match $editorOnlyPattern }).Count -eq 0) {
        $violations += $item
    }
}

Write-Host "[plugin-constraints] $($expected.Count) MCP bridge DLL(s) declared by $nugetRel/.nuget-installed.json"

if ($violations.Count -eq 0 -and $missing.Count -eq 0) {
    Write-Host "[plugin-constraints] PASS — every bridge DLL is UNITY_EDITOR-only."
    exit 0
}

Write-Host ""
Write-Host "[plugin-constraints] FAIL — $($violations.Count + $missing.Count) MCP bridge DLL(s) would be compiled into every player."
Write-Host "Player builds will fail in the managed linker ('Failed to resolve assembly'), and any"
Write-Host "build that did link would carry an HTTP bridge with a Roslyn compiler into the game."
Write-Host ""

foreach ($v in $violations) {
    Write-Host "  $nugetRel/$($v.Dll)  [$($v.Package)]  — .meta has no UNITY_EDITOR constraint"
}
foreach ($m in $missing) {
    Write-Host "  $nugetRel/$($m.Dll)  [$($m.Package)]  — no .meta at all"
}

Write-Host ""
Write-Host "FIX: in each .meta above, replace"
Write-Host ""
Write-Host "         defineConstraints: []"
Write-Host ""
Write-Host "     with"
Write-Host ""
Write-Host "         defineConstraints:"
Write-Host "         - UNITY_EDITOR"
Write-Host ""
Write-Host "     matching R3.dll.meta and ReflectorNet.dll.meta, which the same installer got right."
Write-Host "     Do NOT instead remove the constraint from the DLLs this one references — that ships"
Write-Host "     the whole closure. See EditorBuild.StripEditorOnlyDefines."

exit 1
