# tools/check-commit-scope.ps1 — validates commit subjects against conventions.md section 1.2.
# OWNER: Dev D (plans/00-shared/conventions.md section 7).
#
# This is an ADVISORY check. It runs in the `style` job of .github/workflows/ci.yml, which is
# marked continue-on-error, so a non-zero exit here reports on the PR and never blocks a
# merge. Run it locally before pushing if you want to fix the message while rebasing is still
# cheap.
#
# Valid subject shape (conventions.md section 1.2):
#     <type>(<scope>): <description>
#     feat(transport): add a 32-bit ack bitfield to the header
#
# Types:  feat fix refactor test docs chore
# Scopes: client transport replication master protocol tools ci
#
# Usage:
#     pwsh tools/check-commit-scope.ps1                                  # HEAD vs origin/develop
#     pwsh tools/check-commit-scope.ps1 -BaseRef origin/main -HeadRef HEAD
#     pwsh tools/check-commit-scope.ps1 -Subject "feat(ci): add matrix"  # check one string

[CmdletBinding()]
param(
    [string]$BaseRef = "origin/develop",
    [string]$HeadRef = "HEAD",

    # Check a single literal subject instead of a git range. Handy while writing the message.
    [string]$Subject,

    # Turn the advisory result into a hard failure. Not used by CI today; here so the team can
    # promote the check later by changing one call site rather than rewriting the script.
    [switch]$Strict
)

$ErrorActionPreference = "Stop"

$VALID_TYPES  = @("feat", "fix", "refactor", "test", "docs", "chore")
$VALID_SCOPES = @("client", "transport", "replication", "master", "protocol", "tools", "ci")

# type(scope): description   — scope is required by section 1.2 ("with the scope being your
# ownership area"), so a bare "feat: ..." is reported too. `!` marks a breaking change.
$pattern = '^(?<type>[a-z]+)(\((?<scope>[^)]+)\))?(?<breaking>!)?: (?<desc>.+)$'

function Test-Subject {
    param([string]$Line)

    # Merge commits are generated by git and by GitHub; they are not authored messages.
    if ($Line -match '^Merge (branch|pull request|remote-tracking)') { return $null }
    # `git revert` generates this shape; the reverted subject is quoted inside it.
    if ($Line -match '^Revert "')                                    { return $null }

    $m = [regex]::Match($Line, $pattern)
    if (-not $m.Success) {
        return "not a conventional commit — expected '<type>(<scope>): <description>'"
    }

    $type  = $m.Groups['type'].Value
    $scope = $m.Groups['scope'].Value
    $desc  = $m.Groups['desc'].Value

    if ($VALID_TYPES -notcontains $type) {
        return "unknown type '$type' — valid: $($VALID_TYPES -join ', ')"
    }
    if ([string]::IsNullOrEmpty($scope)) {
        return "missing scope — valid: $($VALID_SCOPES -join ', ')"
    }
    if ($VALID_SCOPES -notcontains $scope) {
        return "unknown scope '$scope' — valid: $($VALID_SCOPES -join ', ')"
    }
    if ($desc.Length -gt 72) {
        return "description is $($desc.Length) chars; keep the subject under 72"
    }
    if ($desc -cmatch '^[A-Z][a-z]') {
        return "description starts with a capital — use lower case ('add the ack bitfield')"
    }
    if ($desc.EndsWith('.')) {
        return "description ends with a period — drop it"
    }

    return $null
}

# ---------------------------------------------------------------------------------------
# Collect the subjects to check
# ---------------------------------------------------------------------------------------
$subjects = @()

if ($Subject) {
    $subjects = @($Subject)
}
else {
    $repoRoot = Split-Path -Parent $PSScriptRoot
    Push-Location $repoRoot
    try {
        # A shallow clone has no merge base with the target branch, so the range silently
        # resolves to nothing and every commit "passes". Detecting that is the whole point of
        # fetch-depth: 0 in ci.yml — say so loudly rather than reporting a false clean.
        $mergeBase = & git merge-base $BaseRef $HeadRef 2>$null
        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($mergeBase)) {
            Write-Warning "No merge base between '$BaseRef' and '$HeadRef'."
            Write-Warning "Either the ref does not exist locally, or this is a shallow clone."
            Write-Warning "In CI, checkout needs fetch-depth: 0. Nothing was checked."
            exit 0
        }

        $raw = & git log "$mergeBase..$HeadRef" --no-merges --format=%s
        if ($LASTEXITCODE -ne 0) { throw "git log failed for range $mergeBase..$HeadRef" }

        $subjects = @($raw | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    }
    finally {
        Pop-Location
    }
}

if ($subjects.Count -eq 0) {
    Write-Host "No commits to check between '$BaseRef' and '$HeadRef'." -ForegroundColor Yellow
    exit 0
}

# ---------------------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------------------
Write-Host "Checking $($subjects.Count) commit subject(s) against conventions.md section 1.2"
Write-Host ""

$problems = @()

foreach ($s in $subjects) {
    $reason = Test-Subject -Line $s
    if ($reason) {
        $problems += [pscustomobject]@{ Subject = $s; Reason = $reason }
        Write-Host "  BAD  $s" -ForegroundColor Yellow
        Write-Host "       -> $reason" -ForegroundColor Yellow
    }
    else {
        Write-Host "  ok   $s" -ForegroundColor Green
    }
}

Write-Host ""

if ($problems.Count -eq 0) {
    Write-Host "All commit subjects conform." -ForegroundColor Green
    exit 0
}

Write-Host "$($problems.Count) of $($subjects.Count) commit subject(s) do not conform." -ForegroundColor Yellow
Write-Host "Fix them with an interactive rebase before merging, or leave them — this check is advisory."
Write-Host "  Valid types:  $($VALID_TYPES -join ' ')"
Write-Host "  Valid scopes: $($VALID_SCOPES -join ' ')"

if ($Strict) { exit 1 }

# Non-zero so the CI step is visibly yellow/red inside the advisory job, while the job's
# continue-on-error keeps the PR mergeable.
exit 1
