#!/usr/bin/env python3
"""Merge the AssetRipper duplicate folders -- but only where Unity says the pair really is a pair.

WHY THIS SCRIPT DOES NOT DECIDE WHAT IS A DUPLICATE

    It cannot. Two rips of the same material never compare equal as text: they carry different
    GUIDs for the same texture and they are in different serialization dialects entirely (the
    canonical `Material/Concrete.mat` is serializedVersion 2 with 5.4's `first:/second:` texenv
    layout; `Material 2/Concrete.mat` is serializedVersion 3). All 120 material and mesh pairs
    differ byte-for-byte, and that fact carries no information.

    So the verdicts come from the Editor -- Ironfront > Recovered Port > Audit Duplicate Assets,
    which loads both sides and compares shader identity, every declared property, mesh topology
    and decoded pixels. This script reads that file and refuses to act on anything it did not
    call `identical`.

WHAT THE AUDIT FOUND, 2026-09-20

    Materials:  0 of 50 identical. Most differ by SHADER -- `Material 2/Concrete.mat` is
                Standard (Specular setup) where `Material/Concrete.mat` is Standard. They are
                not two copies of one material; they are two different materials. Merging them
                would change how the game looks.
    Textures:   1 of 28 identical. The source PNGs ARE byte-identical, but the import settings
                are not (serializedVersion 4 vs 13, different maxTextureSize), so the imported
                textures differ. Picking a winner is a visual decision, not a cleanup.
    Meshes:     44 of 53 identical by topology, bounds and geometry hash. These are mergeable.
    Images3:    referenced by nothing at all -- 16 files of dead weight.

    The phase plan expected the duplicate MATERIAL folders to be blocking batching. They are
    not, because they are not duplicates. That is a finding, not an obstacle to route around.

Usage:
    python tools/dedupe_assets.py --audit      # reference counts + a plan, changes nothing
    python tools/dedupe_assets.py --apply      # execute the plan
    python tools/dedupe_assets.py --verify     # no reference survives to anything we deleted
"""
import argparse
import json
import os
import pathlib
import re
import sys
from collections import Counter

REPO = pathlib.Path(__file__).resolve().parent.parent
ASSETS = REPO / "Ironfront_Reborn" / "Assets"
AUDIT = REPO / "tools" / "recovered" / "duplicate-assets.json"
PLAN = REPO / "tools" / "recovered" / "duplicate-assets-plan.json"

# Every file type that can hold a {fileID, guid} reference.
REFERENCING_SUFFIXES = (
    ".unity", ".prefab", ".mat", ".asset", ".controller", ".anim",
    ".playable", ".overrideController", ".mask", ".physicMaterial",
)

GUID_RE = re.compile(r"guid:\s*([0-9a-f]{32})")


def read_text(path):
    """utf-8-sig on the way in so an existing BOM is consumed rather than doubled."""
    with open(path, "r", encoding="utf-8-sig", errors="surrogateescape", newline="") as fh:
        return fh.read()


def write_text(path, text):
    """Plain utf-8, newline='' -- the file keeps the line endings it arrived with, and gains no BOM."""
    with open(path, "w", encoding="utf-8", errors="surrogateescape", newline="") as fh:
        fh.write(text)


def referencing_files():
    for root, dirs, files in os.walk(ASSETS):
        dirs[:] = [d for d in dirs if d != ".git"]
        for f in files:
            if f.endswith(REFERENCING_SUFFIXES):
                yield pathlib.Path(root) / f


def load_audit():
    if not AUDIT.exists():
        sys.exit(
            "no audit at %s\n"
            "Run it in the Editor first: Ironfront > Recovered Port > Audit Duplicate Assets.\n"
            "This script will not guess which pairs are really pairs." % AUDIT
        )
    return json.loads(read_text(AUDIT))


def count_references(guids):
    """How many times each guid is referenced by an asset OTHER than its own .meta."""
    counts = Counter()
    holders = {g: set() for g in guids}
    for path in referencing_files():
        try:
            text = read_text(path)
        except OSError:
            continue
        for g in set(GUID_RE.findall(text)):
            if g not in holders:
                continue
            counts[g] += len(re.findall(r"guid:\s*%s" % g, text))
            holders[g].add(str(path.relative_to(REPO)).replace("\\", "/"))
    return counts, holders


def build_plan():
    audit = load_audit()
    pairs = audit["pairs"]
    guids = {p["duplicateGuid"] for p in pairs if p["duplicateGuid"]}
    counts, holders = count_references(guids)

    plan = {
        "note": "Generated by tools/dedupe_assets.py --audit. Verdicts come from the Editor audit; "
                "this file only adds reference counts and the resulting action.",
        "auditedAtUtc": audit.get("auditedAtUtc"),
        "actions": [],
    }

    for p in pairs:
        dup_guid = p["duplicateGuid"]
        refs = counts.get(dup_guid, 0)
        entry = {
            "duplicate": p["duplicate"],
            "canonical": p["canonical"],
            "duplicateGuid": dup_guid,
            "canonicalGuid": p["canonicalGuid"],
            "duplicateFileId": p.get("duplicateFileId", 0),
            "canonicalFileId": p.get("canonicalFileId", 0),
            "verdict": p["verdict"],
            "references": refs,
            "referencedBy": sorted(holders.get(dup_guid, ()))[:6],
        }

        if refs == 0:
            entry["action"] = "delete-orphan"
            entry["why"] = "nothing in the project references it"
        elif p["verdict"] == "identical" and p["canonicalGuid"]:
            entry["action"] = "remap"
            entry["why"] = "the Editor audit found it identical to its canonical counterpart: " + p["detail"]
        else:
            entry["action"] = "keep"
            entry["why"] = "%s (%s) and %d live reference(s)" % (p["verdict"], p["detail"], refs)

        plan["actions"].append(entry)

    plan["summary"] = dict(Counter(a["action"] for a in plan["actions"]))
    return plan


def cmd_audit(_args):
    plan = build_plan()
    PLAN.parent.mkdir(parents=True, exist_ok=True)
    write_text(PLAN, json.dumps(plan, indent=2) + "\n")

    print("plan -> %s" % PLAN.relative_to(REPO))
    print("  " + ", ".join("%s=%d" % kv for kv in sorted(plan["summary"].items())))
    for action in ("remap", "delete-orphan"):
        rows = [a for a in plan["actions"] if a["action"] == action]
        if not rows:
            continue
        print("\n%s (%d):" % (action, len(rows)))
        for a in rows[:60]:
            print("   %-46s refs=%-5d %s" % (a["duplicate"].replace("Assets/", ""), a["references"], a["verdict"]))
        if len(rows) > 60:
            print("   ... and %d more" % (len(rows) - 60))

    kept = [a for a in plan["actions"] if a["action"] == "keep"]
    if kept:
        print("\nkeeping %d (not duplicates, or in use):" % len(kept))
        for a in kept[:12]:
            print("   %-46s %s" % (a["duplicate"].replace("Assets/", ""), a["why"][:90]))
        if len(kept) > 12:
            print("   ... and %d more -- see the plan file" % (len(kept) - 12))
    return 0


def cmd_apply(_args):
    if not PLAN.exists():
        sys.exit("no plan at %s -- run --audit first" % PLAN)
    plan = json.loads(read_text(PLAN))

    remaps = [a for a in plan["actions"] if a["action"] == "remap"]
    orphans = [a for a in plan["actions"] if a["action"] == "delete-orphan"]
    if not remaps and not orphans:
        print("nothing to do")
        return 0

    # --- rewrite references -------------------------------------------------------------------
    # Both halves of the reference move together. A guid-only swap would leave a local file id
    # the canonical asset does not contain, and Unity resolves that to nothing at all: a missing
    # mesh, silently, at load.
    substitutions = []
    for a in remaps:
        if not a["canonicalGuid"]:
            sys.exit("remap %s has no canonical guid -- refusing" % a["duplicate"])
        substitutions.append((
            re.compile(r"fileID:\s*%d\s*,\s*guid:\s*%s" % (a["duplicateFileId"], a["duplicateGuid"])),
            "fileID: %d, guid: %s" % (a["canonicalFileId"], a["canonicalGuid"]),
        ))

    rewritten = 0
    replacements = 0
    for path in referencing_files():
        try:
            text = read_text(path)
        except OSError:
            continue
        original = text
        for pattern, repl in substitutions:
            text, n = pattern.subn(repl, text)
            replacements += n
        if text != original:
            write_text(path, text)
            rewritten += 1
    print("rewrote %d reference(s) across %d file(s)" % (replacements, rewritten))

    # --- delete ------------------------------------------------------------------------------
    deleted = 0
    for a in remaps + orphans:
        target = REPO / "Ironfront_Reborn" / a["duplicate"]
        for p in (target, target.with_name(target.name + ".meta")):
            if p.exists():
                p.unlink()
                deleted += 1
    print("deleted %d file(s) (%d assets + their .meta)" % (deleted, len(remaps) + len(orphans)))

    # A folder that now holds nothing but .meta files is finished with.
    for folder in sorted({(REPO / "Ironfront_Reborn" / a["duplicate"]).parent for a in remaps + orphans}):
        if folder.exists() and not any(p for p in folder.iterdir() if p.suffix != ".meta"):
            for p in folder.iterdir():
                p.unlink()
            folder.rmdir()
            meta = folder.with_name(folder.name + ".meta")
            if meta.exists():
                meta.unlink()
            print("removed now-empty folder %s" % folder.relative_to(REPO))

    print("\nRun `python tools/dedupe_assets.py --verify`, then refresh the Editor.")
    return 0


def cmd_verify(_args):
    if not PLAN.exists():
        sys.exit("no plan at %s" % PLAN)
    plan = json.loads(read_text(PLAN))
    gone = {a["duplicateGuid"]: a["duplicate"] for a in plan["actions"] if a["action"] in ("remap", "delete-orphan")}
    if not gone:
        print("plan removed nothing; nothing to verify")
        return 0

    counts, holders = count_references(set(gone))
    dangling = {g: n for g, n in counts.items() if n > 0}
    if dangling:
        print("FAIL -- %d deleted asset(s) are still referenced:" % len(dangling))
        for g, n in sorted(dangling.items(), key=lambda kv: -kv[1]):
            print("   %-46s %d ref(s) in %s" % (gone[g], n, ", ".join(sorted(holders[g])[:3])))
        return 1

    still_on_disk = [p for a in plan["actions"] if a["action"] in ("remap", "delete-orphan")
                     for p in [REPO / "Ironfront_Reborn" / a["duplicate"]] if p.exists()]
    if still_on_disk:
        print("FAIL -- %d file(s) the plan removed are still on disk" % len(still_on_disk))
        return 1

    print("OK -- %d removed asset(s), zero surviving references" % len(gone))
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--audit", action="store_true", help="count references and write the plan")
    g.add_argument("--apply", action="store_true", help="execute the plan")
    g.add_argument("--verify", action="store_true", help="assert nothing still references what was removed")
    args = ap.parse_args(argv)

    if args.audit:
        return cmd_audit(args)
    if args.apply:
        return cmd_apply(args)
    return cmd_verify(args)


if __name__ == "__main__":
    sys.exit(main())
